#!/usr/bin/env bash

# Finds any definition that contains the word specified in the parameter.
# Call from TypeTopology/source.

set -Eeo pipefail

param="$1"

regex="^[[:space:]]*[^(){}]*${param}.* :"

# This means "newline followed by zero or more spaces, then zero or
# more characters that are not brackets, followed by the specified
# word, following by zero or more occurences of anything,
# followed by " :".

echo $regex

git ls-files . | grep agda | xargs grep -E "$regex"
