#!/usr/bin/env bash

# This simple-minded script parallelizes the type checking of this repository,
# significantly reducing the type checking time.
#
# According to
#
# https://agda.zulipchat.com/#narrow/channel/238741-general/topic/How.20safe.20is.20this.3F.20.28Brute-force.20parallelism.2E.29/with/563647851
#
# this script is safe in the sense of being immune to race conditions.
#
# Currently, as of 2025-12-13, in a Mac M4 Mini (not Pro) with 24GB of ram, running just
#
#  $ agda AllModulesIndex.lagda
#
# takes 6:00 min.
#
# But running this script takes only 3:40 min instead.
#
# Run
#
#  $ time ../do-all-in-parallel
#
# from ~/TypeTopology/source to verify this.
#
# I get the same time behavior in a MacBook Air M4 with 32GB of ram.
#
# This is useful when we change a file that forces almost all files to be type checked again.
#
# I haven't tried it in other operating systems or hardware.
#
# Feedback from users of other hardware and/or operating systems is welcome.
# (Do a pull request to report it, or contact me directly, and I will add it here.)
#
# Added 14th December 2025. I have now tested this in a 2012 Intel
# machine running Linux (Ubuntu 24.04) with 16GB of ram, namely
# Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz with four cores.
#
#  $ time ../do-all-in-parallel
#    real 16m28s
#    user 54m13s
#    sys  0m29s
#
#  $ rm -rf ../_build/
#  $ time agda AllModulesIndex
#    real 18m27s
#    user 18m23s
#    sys  0m5s
#
# So not a significant difference in this case. But still a minor improvement.
#
# I still wonder what happens in more modern Intel machines, and also
# in Apple's "Pro" and "Max" machines (which I don't own and I don't
# plan to).

agda AllModulesIndex.lagda &
agda ContinuityAxiom/index.lagda &
agda DiscreteGraphicMonoids/index.lagda &
agda DomainTheory/index.lagda &
agda EffectfulForcing/index.lagda &
agda Games/index.lagda &
agda GamesMGU/index.lagda &
agda Groups/index.lagda &
agda Higgs/index.lagda &
agda InfinitePigeon/index.agda &
agda InjectiveTypes/index.lagda &
agda Locales/index.lagda &
agda MGS/index.lagda &
agda Ordinals/index.lagda &
agda PCF/index.lagda &
agda TWA/index.lagda &
agda TypeTopology/index.lagda &
agda UF/index.lagda &
agda Various/index.lagda &

wait

# I tried adding more index modules above, but this slows things down.
# The above is a result of trial-and-error to optimize time.
# It is possible that other choices of files to typecheck in parallel may improve things further.
# In any case, whatever the choices, it is important to always include `AllModulesIndex`.
