#!/bin/bash

# Generate html files and deploy them.
# This is to be run from TypeTopology/source.
# It assumes that we want to deploy the html pages at ~/public_html.

rm -rf html
agda --highlight-occurrences --html AllModulesIndex.lagda
rm ~/public_html/TypeTopology/*.html # do not delete Agda.css, as it is a modified version
mv html/*.html ~/public_html/TypeTopology/
chmod a+r ~/public_html/TypeTopology/*.html

# Now create symlinks for files that have been moved to other places
# but are linked from published papers, blogs etc.

cd ~/public_html/TypeTopology/

ln -s CantorSchroederBernstein.CSB.html CantorSchroederBernstein.html
ln -s CoNaturals.GenericConvergentSequence.html GenericConvergentSequence.html
ln -s Games.FiniteHistoryDependent.html FiniteHistoryDependentGames.html
ln -s Groups.FreeGroup.html FreeGroup.html
ln -s Groups.FreeGroupOfLargeLocallySmallSet.html FreeGroupOfLargeLocallySmallSet.html
ln -s Locales.AdjointFunctorTheoremForFrames.html AdjointFunctorTheoremForFrames.html
ln -s Locales.CompactRegular.html CompactRegular.html
ln -s Locales.Frame.html Frame.html
ln -s Locales.GaloisConnection.html GaloisConnection.html
ln -s Locales.HeytingImplication.html HeytingImplication.html
ln -s MLTT.Fin.html Fin.html
ln -s MLTT.Fin-Properties.html Fin-Properties.html
ln -s NotionsOfDecidability.SemiDecidable.html SemiDecidable.html
ln -s Ordinals.index.html Ordinals.html
ln -s Ordinals.Arithmetic-Properties.html OrdinalArithmetic-Properties.html
ln -s Ordinals.BuraliForti.html BuraliForti.html
ln -s Ordinals.Notions.html Ordinal-Notions.html
ln -s Ordinals.OrdinalOfOrdinals.html OrdinalOfOrdinals.html
ln -s Ordinals.WellOrderTransport.html OrdinalsWellOrderTransport.html
ln -s DomainTheory.ScottModelOfPCF.ScottModelOfPCF.html PCFModules.html
ln -s Redirection.Types2019.html Types2019.html
ln -s Slice.Slice.html Slice.html
ln -s TypeTopology.DiscreteAndSeparated.html DiscreteAndSeparated.html
ln -s TypeTopology.GenericConvergentSequenceCompactness.html ConvergentSequenceCompac.html
ln -s UF.Choice.html UF-Choice.html
ln -s UF.Factorial.html UF-Factorial.html
ln -s UF.Size.html UF-Size.html
ln -s UF.UniverseEmbedding.html UniverseEmbedding.html
ln -s UF.Yoneda.html UF-Yoneda.html
ln -s UF.index.html UF.html
ln -s Uncatalogued.ArithmeticViaEquivalence.html ArithmeticViaEquivalence.html
ln -s Uncatalogued.Dedekind.html Dedekind.html
ln -s Uncatalogued.HiggsInvolutionTheorem.html HiggsInvolutionTheorem.html
ln -s Uncatalogued.LawvereFPT.html LawvereFPT.html
ln -s Uncatalogued.UnivalenceFromScratch.html UnivalenceFromScratch.html
