#!/bin/bash

# Generate html files and deploy them.
# This is to be run from TypeTopology/source.
# It assumes that we want to deploy the html pages at ~/public_html.

rm -rf html
agda --highlight-occurrences --html AllModulesIndex.lagda
rm -rf ~/public_html/TypeTopology/*.html
mv html/*.html ~/public_html/TypeTopology/
chmod a+r ~/public_html/TypeTopology/*

# Now create symlinks for files that have been moved to other places
# but are linked from published papers, blogs etc.

cd ~/public_html/TypeTopology/source

ln -s Ordinals.Types2019.html Types2019.html
ln -s NotionsOfDecidability.SemiDecidable.html SemiDecidable.html
ln -s Uncatalogued.Dedekind.html Dedekind.html
ln -s Uncatalogued.LawvereFPT.html LawvereFPT.html
ln -s Uncatalogued.HiggsInvolutionTheorem.html HiggsInvolutionTheorem.html
ln -s CantorSchroederBernstein.CSB.html CantorSchroederBernstein.html
ln -s UF.Size.html UF-Size.html
ln -s TypeTopology.DiscreteAndSeparated.html DiscreteAndSeparated.html
ln -s Slice.Slice.html Slice.html
ln -s PCFModules DomainTheory.ScottModelOfPCF.ScottModelOfPCF.html PCFModules
ln -s Locales.Frame.html Frame.html
ln -s Locales.GaloisConnection.html GaloisConnection.html
ln -s Locales.AdjointFunctorTheoremForFrames.html AdjointFunctorTheoremForFrames.html
ln -s Locales.CompactRegular.html CompactRegular.html
ln -s Locales.HeytingImplication.html HeytingImplication.html
ln -s Ordinals.BuraliForti.html BuraliForti.html
ln -s Ordinals.Notions.html Ordinal-Notions.html
ln -s Ordinals.OrdinalOfOrdinals.html OrdinalOfOrdinals.html
ln -s Ordinals.WellOrderTransport.html OrdinalsWellOrderTransport.html
ln -s UF.UniverseEmbedding.html UniverseEmbedding.html
ln -s Ordinals.Arithmetic-Properties.html OrdinalArithmetic-Properties.html
ln -s Groups.FreeGroup.html FreeGroup.html
ln -s Groups.FreeGroupOfLargeLocallySmallSet.html FreeGroupOfLargeLocallySmallSet.html
ln -s Uncatalogued.UnivalenceFromScratch.html UnivalenceFromScratch.html
ln -s UF.index.html UF.html
ln -s UF.Choice.html UF-Choice.html
