#!/bin/bash

ghc --make agdatomd.hs

inotifywait -e close_write,moved_to,create -m . |
while read -r directory events filename; do
  if [ "$filename" = "HoTT-UF-Agda.lagda" ]; then
    date
    agda --html --html-highlight=code HoTT-UF-Agda.lagda && cp html/HoTT-UF-Agda.tex HoTT-UF-Agda.md && cp html/Universes.tex Universes.md
    echo "done"
  fi
done
