#!/bin/bash

ghc --make agdatomd.hs

generatemd () {
    cat MLTT-Agda.lagda | ./agdatomd > ../MLTT-Agda.md
    cat HoTT-UF-Agda.lagda | ./agdatomd > ../HoTT-UF-Agda.md
    cat Universes.lagda | ./agdatomd > ../Universes.md
    cat FunExt.lagda | ./agdatomd > ../FunExt.md
    cat Appendix.lagda | ./agdatomd > ../Appendix.md
    cat Inhabitation.lagda | ./agdatomd > ../Inhabitation.md
    }

generatemd

inotifywait -e close_write,moved_to,create -m . |
while read -r directory events filename; do
    if [ "$filename" = "HoTT-UF-Agda.lagda" ] ||
       [ "$filename" = "MLTT-Agda.lagda" ] ||
       [ "$filename" = "Universes.lagda" ] ||
       [ "$filename" = "FunExt.lagda" ] ||
       [ "$filename" = "Inhabitation.lagda" ] ||
       [ "$filename" = "Appendix.lagda" ] ; then
      date
      generatemd
    echo "done"
  fi
done
