#!/bin/bash
#!/bin/bash

#!/bin/bash

ghc --make illiterator.hs

./illiterate

inotifywait -e close_write,moved_to,create -m . |
while read -r directory events filename; do
    if [ "$filename" = "HoTT-UF-Agda.lagda" ] ||
       [ "$filename" = "MLTT-Agda.lagda" ] ||
       [ "$filename" = "Universes.lagda" ] ||
       [ "$filename" = "FunExt.lagda" ] ||
       [ "$filename" = "Inhabitation.lagda" ] ||
       [ "$filename" = "Appendix.lagda" ] ; then
      date
      ./illiterate
    echo "done"
  fi
done
