#!/usr/bin/env bash

# Martin Escardo 6th May 2026.

# Generates a Haskell file with the dependency graph of all modules,
# after transitive reduction.

set -Eeo pipefail

agda ../source/AllModulesIndex.lagda --dependency-graph=graph.dot

tred graph.dot > reduced-graph.dot

echo "-- This file is automatically generated by ./convert.hs." > DependencyGraph.hs
echo ""                                                        >> DependencyGraph.hs
echo "module DependencyGraph where"                            >> DependencyGraph.hs
echo ""                                                        >> DependencyGraph.hs
echo "labels :: [(Int,String)]"                                >> DependencyGraph.hs
echo "labels = ["                                              >> DependencyGraph.hs

grep "label" reduced-graph.dot \
     | sed 's/\[label=AllModulesIndex\]/[label="AllModulesIndex"]/' \
     | sed 's/\[label=index\]/[label="index"]/' \
     | sed 's/\[label=/ , /' \
     | sed 's/];/),/' \
     | sed 's/\tm/  (/' \
     | sed '$s/\(.*\),/\1]/' \
     | sed 's/\t/ /g' \
    >> DependencyGraph.hs

echo ""                             >> DependencyGraph.hs
echo "dependencies :: [(Int,Int)]"  >> DependencyGraph.hs
echo "dependencies = ["             >> DependencyGraph.hs

grep "\->" reduced-graph.dot \
     | sed 's/\tm/  (/' \
     | sed 's/->/,/' \
     | sed 's/;/),/' \
     | sed 's/m//g' \
     | sed '$s/\(.*\),/\1]/' \
    >> DependencyGraph.hs
