Martin Escardo, 04 January 2021.

Ongoing joint work with Marc Bezem, Thierry Coquand, and Peter Dybjer.

We construct free groups in HoTT/UF in Agda without HIT's other than
propositional truncation.

Based on Richman's book on constructive algebra.

For the moment this file is not for public consumption, but it is
publicly visible.

This is part of the Martin Escardo's Agda development TypeTopology,
whose philosophy is to be Spartan. At the moment we are a bit
Athenian, though, although we intend to fix this in the
future.

\begin{code}

{-# OPTIONS --without-K --safe #-} -- --exact-split

\end{code}

NB. This repository is supposed to use exact-split, but even though
everything has been developed using case-split, the exact-split check
fails (in Agda 2.6.1) in the helper function f of the function
churros. This seems to be a bug.

\begin{code}

open import UF-PropTrunc
open import UF-Univalence

module FreeGroup
       (pt : propositional-truncations-exist)
       (ua : Univalence)
       where

open import SpartanMLTT
open import Two
open import Two-Properties

open import UF-Base
open import UF-Subsingletons
open import UF-Equiv
open import UF-UA-FunExt
open import UF-FunExt

\end{code}

It is possible to work with lists *defined* from the ingredients of
our Spartan MLTT (see the module Fin.lagda). For the moment we are
Athenian in this respect:

\begin{code}

data List {𝓤} (X : 𝓤 ̇ ) : 𝓤 ̇  where
 [] : List X
 _∷_ : X → List X → List X

infixr 2 _∷_

equal-heads : {X : 𝓤 ̇ } {x y : X} {s t : List X}
            → x ∷ s ≡ y ∷ t
            → x ≡ y
equal-heads {𝓤} {X} {x} = ap f
 where
  f : List X → X
  f []      = x
  f (z ∷ _) = z

equal-tails : {X : 𝓤 ̇ } {x y : X} {s t : List X}
            → x ∷ s ≡ y ∷ t
            → s ≡ t
equal-tails {𝓤} {X} = ap f
 where
  f : List X → List X
  f []      = []
  f (_ ∷ u) = u

[_] : {X : 𝓤 ̇ } → X → List X
[ x ] = x ∷ []

_++_ : {X : 𝓤 ̇ } → List X → List X → List X
[]      ++ t = t
(x ∷ s) ++ t = x ∷ (s ++ t)

infixr 4 _++_

[]-right-neutral : {X : 𝓤 ̇ } (s : List X) → s ≡ s ++ []
[]-right-neutral []      = refl
[]-right-neutral (x ∷ s) = ap (x ∷_) ([]-right-neutral s)

++-assoc : {X : 𝓤 ̇ } → associative (_++_ {𝓤} {X})
++-assoc []      t u = refl
++-assoc (x ∷ s) t u = ap (x ∷_) (++-assoc s t u)

\end{code}

We now construct the group freely generated by a set A. The set-hood
requirement is needed later only, and so we don't include it as an
assumption in the following anonymous module:

\begin{code}

module _ {𝓤 : Universe}
         {A : 𝓤 ̇ }
       where

 X : 𝓤 ̇
 X = 𝟚 × A

 _⁻ : X → X
 (n , a)⁻ = (complement n , a)

 inv-invol : (x : X) → (x ⁻)⁻ ≡ x
 inv-invol (n , a) = ap (_, a) (complement-involutive n)

\end{code}

We will quotient the following type FA to get the undelying type of
the free group:

\begin{code}

 FA : 𝓤 ̇
 FA = List X

 η : A → FA
 η a = [ ₀ , a ]

\end{code}

We will quotient by the equivalence relation generated by the
following reduction relation:

\begin{code}

 _▷_ : FA → FA → 𝓤 ̇
 s ▷ t = Σ u ꞉ FA , Σ v ꞉ FA , Σ x ꞉ X , (s ≡ u ++ [ x ] ++ [ x ⁻ ] ++ v)
                                       × (t ≡ u ++ v)

 infix 1 _▷_

 ∷-▷ : {s t : FA} (x : X) → s ▷ t → x ∷ s ▷ x ∷ t
 ∷-▷ x (u , v , y , p , q) = (x ∷ u) , v , y , ap (x ∷_) p , ap (x ∷_) q

\end{code}

The following is a lemma for the Church-Rosser property, proved by
induction on u₀ and u₁:

\begin{code}

 churros : (u₀ v₀ u₁ v₁ : FA) (x₀ x₁ : X)

         → u₀ ++  [ x₀ ] ++ [ x₀ ⁻ ] ++ v₀
         ≡ u₁ ++  [ x₁ ] ++ [ x₁ ⁻ ] ++ v₁

         → (u₀ ++ v₀ ≡ u₁ ++ v₁)
         + (Σ t ꞉ FA , (u₀ ++ v₀ ▷ t) × (u₁ ++ v₁ ▷ t))

 churros u₀ v₀ u₁ v₁ x₀ x₁ = f u₀ u₁
  where
   f : (u₀ u₁ : FA)
     → u₀ ++  [ x₀ ] ++ [ x₀ ⁻ ] ++ v₀ ≡ u₁ ++  [ x₁ ] ++ [ x₁ ⁻ ] ++ v₁
     → (u₀ ++ v₀ ≡ u₁ ++ v₁) + (Σ t ꞉ FA , (u₀ ++ v₀ ▷ t) × (u₁ ++ v₁ ▷ t))

   f [] [] p = inl γ
    where
     have : x₀ ∷ x₀ ⁻  ∷ v₀
          ≡ x₁ ∷ x₁ ⁻  ∷ v₁
     have = p

     γ : v₀ ≡ v₁
     γ = equal-tails (equal-tails p)

   f [] (y₁ ∷ []) p = inl γ
    where
     have : x₀ ∷ x₀ ⁻ ∷ v₀
          ≡ y₁ ∷ x₁   ∷ x₁ ⁻ ∷ v₁
     have = p

     q = x₁ ⁻     ≡⟨ ap _⁻ ((equal-heads (equal-tails p))⁻¹) ⟩
         (x₀ ⁻) ⁻ ≡⟨ inv-invol x₀ ⟩
         x₀       ≡⟨ equal-heads p ⟩
         y₁       ∎

     γ : v₀ ≡ y₁ ∷ v₁
     γ = transport (λ - → v₀ ≡ - ∷ v₁) q (equal-tails (equal-tails p))

   f [] (y₁ ∷ z₁ ∷ u₁) p = inr γ
    where
     have : x₀ ∷ x₀ ⁻ ∷ v₀
          ≡ y₁ ∷ z₁   ∷ u₁ ++ [ x₁ ] ++ [ x₁ ⁻ ] ++ v₁
     have = p

     d' : u₁ ++ [ x₁ ] ++ [ x₁ ⁻ ] ++ v₁ ▷ u₁ ++ v₁
     d' = u₁ , v₁ , x₁ , refl , refl

     d : v₀ ▷ u₁ ++ v₁
     d = transport (_▷ u₁ ++ v₁) ((equal-tails (equal-tails p))⁻¹) d'

     q = y₁ ⁻ ≡⟨ (ap (_⁻) (equal-heads p)⁻¹) ⟩
         x₀ ⁻ ≡⟨ equal-heads (equal-tails p) ⟩
         z₁   ∎

     e' : y₁ ∷ y₁ ⁻ ∷ u₁ ++ v₁ ▷ u₁ ++ v₁
     e' = [] , (u₁ ++ v₁) , y₁ , refl , refl

     e : y₁ ∷ z₁ ∷ u₁ ++ v₁ ▷ u₁ ++ v₁
     e = transport (λ - → y₁ ∷ - ∷ u₁ ++ v₁ ▷ u₁ ++ v₁) q e'

     γ : Σ t ꞉ FA , (v₀ ▷ t) × (y₁ ∷ z₁ ∷ u₁ ++ v₁ ▷ t)
     γ = (u₁ ++ v₁) , d , e

   f (y₀ ∷ []) [] p = inl γ
    where
     have : y₀ ∷ x₀   ∷ x₀ ⁻ ∷ v₀
          ≡ x₁ ∷ x₁ ⁻ ∷ v₁
     have = p

     γ = y₀ ∷ v₀       ≡⟨ ap (_∷ v₀) (equal-heads p) ⟩
         x₁ ∷ v₀       ≡⟨ ap (_∷ v₀) ((inv-invol x₁)⁻¹) ⟩
         (x₁ ⁻) ⁻ ∷ v₀ ≡⟨ ap (λ - → - ⁻ ∷ v₀) ((equal-heads (equal-tails p))⁻¹) ⟩
         x₀ ⁻ ∷ v₀     ≡⟨ equal-tails (equal-tails p) ⟩
         v₁            ∎

   f (y₀ ∷ z₀ ∷ u₀) [] p = inr γ
    where
     have : y₀ ∷ z₀   ∷ u₀ ++ [ x₀ ] ++ [ x₀ ⁻ ] ++ v₀
          ≡ x₁ ∷ x₁ ⁻ ∷ v₁
     have = p

     q = y₀ ⁻ ≡⟨ ap (_⁻) (equal-heads p) ⟩
         x₁ ⁻ ≡⟨ (equal-heads (equal-tails p))⁻¹ ⟩
         z₀   ∎

     d' : y₀ ∷ y₀ ⁻ ∷ u₀ ++ v₀ ▷ u₀ ++ v₀
     d' = [] , (u₀ ++ v₀) , y₀ , refl , refl

     d : y₀ ∷ z₀ ∷ u₀ ++ v₀ ▷ u₀ ++ v₀
     d = transport (λ - → y₀ ∷ - ∷ u₀ ++ v₀ ▷ u₀ ++ v₀) q d'

     e' : u₀ ++ [ x₀ ] ++ [ x₀ ⁻ ] ++ v₀ ▷ u₀ ++ v₀
     e' = u₀ , v₀ , x₀ , refl , refl

     e : v₁ ▷ u₀ ++ v₀
     e = transport (_▷ u₀ ++ v₀) (equal-tails (equal-tails p)) e'

     γ : Σ t ꞉ FA , (y₀ ∷ z₀ ∷ u₀ ++ v₀ ▷ t) × (v₁ ▷ t)
     γ = (u₀ ++ v₀) , d , e

   f (y₀ ∷ u₀) (y₁ ∷ u₁) p = γ
    where
     have : y₀ ∷ u₀ ++ [ x₀ ] ++ [ x₀ ⁻ ] ++ v₀
          ≡ y₁ ∷ u₁ ++ [ x₁ ] ++ [ x₁ ⁻ ] ++ v₁
     have = p

     IH : (u₀ ++ v₀ ≡ u₁ ++ v₁) + (Σ t ꞉ FA , (u₀ ++ v₀ ▷ t) × (u₁ ++ v₁ ▷ t))
     IH = f u₀ u₁ (equal-tails p)

     Γ : X → X → 𝓤 ̇
     Γ y₀ y₁ = (y₀ ∷ u₀ ++ v₀ ≡ y₁ ∷ u₁ ++ v₁)
             + (Σ t ꞉ FA , (y₀ ∷ u₀ ++ v₀ ▷ t) × (y₁ ∷ u₁ ++ v₁ ▷ t))

     δ : type-of IH → ∀ {y₀ y₁} → y₀ ≡ y₁ → Γ y₀ y₁
     δ (inl q)           {y₀} refl = inl (ap (y₀ ∷_) q)
     δ (inr (t , d , e)) {y₀} refl = inr ((y₀ ∷ t) , ∷-▷ y₀ d , ∷-▷ y₀ e)

     γ : Γ y₀ y₁
     γ = δ IH (equal-heads p)

 Church-Rosser : (s t₀ t₁ : FA)
               → s ▷ t₀
               → s ▷ t₁
               → (t₀ ≡ t₁) + (Σ t ꞉ FA , (t₀ ▷ t) × (t₁ ▷ t))
 Church-Rosser s t₀ t₁ (u₀ , v₀ , x₀ , p₀ , q₀) (u₁ , v₁ , x₁ , p₁ , q₁) = γ δ
  where
   δ : (u₀ ++ v₀ ≡ u₁ ++ v₁) + (Σ t ꞉ FA , (u₀ ++ v₀ ▷ t) × (u₁ ++ v₁ ▷ t))
   δ = churros u₀ v₀ u₁ v₁ x₀ x₁ (p₀ ⁻¹ ∙ p₁)

   γ : type-of δ → (t₀ ≡ t₁) + (Σ t ꞉ FA , (t₀ ▷ t) × (t₁ ▷ t))
   γ (inl q)           = inl (q₀ ∙ q ∙ q₁ ⁻¹)
   γ (inr (t , p , q)) = inr (t , transport (_▷ t) (q₀ ⁻¹) p ,
                                  transport (_▷ t) (q₁ ⁻¹) q)

\end{code}

The symmetric closure of _▷_:

\begin{code}

 open import SRTclosure

 _◁▷_ : FA → FA → 𝓤 ̇
 _◁▷_ = s-closure _▷_

 infix 1 _◁▷_

\end{code}

Symmetric, reflexive, transitive closure of _▷_:

\begin{code}

 open psrt pt

 _∾_ : FA → FA → 𝓤 ̇
 _∾_ = srt-closure _▷_

\end{code}

Propositional, symmetric, reflexive, transitive closure of _▷_:

\begin{code}

 _∾ₚ_ : FA → FA → 𝓤 ̇
 _∾ₚ_ = psrt-closure _▷_

\end{code}

The above is just the truncation of _∾_. Most of the work will be done
before truncation. The following is for reasoning with chain of
equivalences:

\begin{code}

 infix 1 _∾_

 _∾⟨_⟩_ : (s : FA) {t u : FA} → s ∾ t → t ∾ u → s ∾ u
 _ ∾⟨ p ⟩ q = srt-transitive _▷_ _ _ _ p q

 _∾∎ : (s : FA) → s ∾ s
 _∾∎ _ = srt-reflexive _▷_ _

 infixr 0 _∾⟨_⟩_
 infix  1 _∾∎

\end{code}

The group operation before quotienting is simply concatenation.

Concatenation is a left congruence:

\begin{code}

 ++-▷-left : (s s' t : FA) → s ▷ s' → s ++ t ▷ s' ++ t
 ++-▷-left s s' t (u , v , x , p , q) = u , (v ++ t) , x , p' , q'
  where
   p' = s ++ t                            ≡⟨ ap (_++ t) p ⟩
        (u ++ [ x ] ++ [ x ⁻ ] ++ v) ++ t ≡⟨ ++-assoc u ([ x ] ++ [ x ⁻ ] ++ v) t ⟩
        u ++ [ x ] ++ [ x ⁻ ] ++ v ++ t   ∎

   q' = s' ++ t       ≡⟨ ap (_++ t) q ⟩
        (u ++ v) ++ t ≡⟨ ++-assoc u v t ⟩
        u ++ v ++ t   ∎

 ++-◁▷-left : (s s' t : FA) → s ◁▷ s' → s ++ t ◁▷ s' ++ t
 ++-◁▷-left s s' t (inl a) = inl (++-▷-left s s' t a)
 ++-◁▷-left s s' t (inr a) = inr (++-▷-left s' s t a)

 ++-iteration-left : (s s' t : FA) (n : ℕ)
                   → iteration _◁▷_ n s s'
                   → iteration _◁▷_ n (s ++ t) (s' ++ t)
 ++-iteration-left s s  t zero     refl        = refl
 ++-iteration-left s s' t (succ n) (u , b , c) = (u ++ t) ,
                                                 ++-◁▷-left s u t b ,
                                                 ++-iteration-left u s' t n c

 ++-cong-left : (s s' t : FA) → s ∾ s' → s ++ t ∾ s' ++ t
 ++-cong-left s s' t (n , a) = n , ++-iteration-left s s' t n a

\end{code}

It is also a right congruence:

\begin{code}

 ∷-◁▷ : (x : X) {s t : FA} → s ◁▷ t → x ∷ s ◁▷ x ∷ t
 ∷-◁▷ x (inl e) = inl (∷-▷ x e)
 ∷-◁▷ x (inr e) = inr (∷-▷ x e)

 ∷-iteration : (x : X) {s t : FA} (n : ℕ)
             → iteration _◁▷_ n s t
             → iteration _◁▷_ n (x ∷ s) (x ∷ t)
 ∷-iteration x zero refl = refl
 ∷-iteration x (succ n) (u , b , c) = (x ∷ u) , ∷-◁▷ x b , ∷-iteration x n c

 ∷-cong : (x : X) {s t : FA} → s ∾ t → x ∷ s ∾ x ∷ t
 ∷-cong x (n , a) = n , ∷-iteration x n a

 ++-cong-right : (s {t t'} : FA) → t ∾ t' → s ++ t ∾ s ++ t'
 ++-cong-right []      e = e
 ++-cong-right (x ∷ s) e = ∷-cong x (++-cong-right s e)

\end{code}

And therefore it is a two-sided congruence:

\begin{code}

 ++-cong : {s s' t t' : FA} → s ∾ s' → t ∾ t' → s ++ t ∾ s' ++ t'
 ++-cong {s} {s'} {t} {t'} d e = s ++ t   ∾⟨ ++-cong-left s s' t d ⟩
                                 s' ++ t  ∾⟨ ++-cong-right s' e ⟩
                                 s' ++ t' ∾∎
\end{code}

The group inverse, before quotienting:

\begin{code}

 inv : FA → FA
 inv [] = []
 inv (x ∷ s) = inv s ++ [ x ⁻ ]

\end{code}

It is a congruence:

\begin{code}

 inv-++ : (s t : FA) → inv (s ++ t) ≡ inv t ++ inv s
 inv-++ []      t = []-right-neutral (inv t)
 inv-++ (x ∷ s) t = inv (s ++ t) ++ [ x ⁻ ]     ≡⟨ IH ⟩
                    (inv t ++ inv s) ++ [ x ⁻ ] ≡⟨ assoc ⟩
                    inv t ++ (inv s ++ [ x ⁻ ]) ∎
  where
   IH    = ap (_++ [ x ⁻ ]) (inv-++ s t)
   assoc = ++-assoc (inv t) (inv s) [ x ⁻ ]

 inv-▷ : {s t : FA} → s ▷ t → inv s ▷ inv t
 inv-▷ {s} {t} (u , v , y , p , q) = inv v , inv u , y , p' , q'
  where
   p' = inv s                                     ≡⟨ I ⟩
        inv (u ++ [ y ] ++ [ y ⁻ ] ++ v)          ≡⟨ II ⟩
        inv ([ y ] ++ [ y ⁻ ] ++ v) ++ inv u      ≡⟨ III ⟩
        inv (([ y ] ++ [ y ⁻ ]) ++ v) ++ inv u    ≡⟨ IV ⟩
        (inv v ++ [ (y ⁻)⁻ ] ++ [ y ⁻ ]) ++ inv u ≡⟨ V ⟩
        (inv v ++ [ y ] ++ [ y ⁻ ]) ++ inv u      ≡⟨ VI ⟩
        inv v ++ [ y ] ++ [ y ⁻ ] ++ inv u        ∎
    where
     I   = ap inv p
     II  = inv-++ u ([ y ] ++ [ y ⁻ ] ++ v)
     III = ap (λ - → inv - ++ inv u) ((++-assoc [ y ] [ y ⁻ ] v)⁻¹)
     IV  = ap (_++ inv u) (inv-++ ([ y ] ++ [ y ⁻ ]) v)
     V   = ap (λ - → (inv v ++ [ - ] ++ [ y ⁻ ]) ++ inv u) (inv-invol y)
     VI  = ++-assoc (inv v) ([ y ] ++ [ y ⁻ ]) (inv u)

   q' = inv t          ≡⟨ ap inv q ⟩
        inv (u ++ v)   ≡⟨ inv-++ u v ⟩
        inv v ++ inv u ∎

 inv-◁▷ : {s t : FA} → s ◁▷ t → inv s ◁▷ inv t
 inv-◁▷ (inl e) = inl (inv-▷ e)
 inv-◁▷ (inr e) = inr (inv-▷ e)

 inv-iteration : {s t : FA} (n : ℕ)
               → iteration _◁▷_ n s t
               → iteration _◁▷_ n (inv s) (inv t)
 inv-iteration zero refl = refl
 inv-iteration (succ n) (u , b , c) = inv u , inv-◁▷ b , inv-iteration n c

 inv-cong : {s t : FA} → s ∾ t → inv s ∾ inv t
 inv-cong (n , a) = n , inv-iteration n a

\end{code}

The inverse really is an inverse:

\begin{code}

 =-∾ : {s s' : FA} → s ≡ s' → s ∾ s'
 =-∾ {s} refl = srt-reflexive _▷_ s

 inv-lemma : (x : X) → [ x ] ++ [ x ⁻ ] ∾ []
 inv-lemma x = srt-extension _▷_ _ [] ([] , [] , x , refl , refl)

 inv-lemma' : (x : X) → [ x ⁻ ] ++ [ x ] ∾ []
 inv-lemma' x = srt-extension _▷_ _ _
                 ([] ,
                  [] ,
                  (x ⁻) ,
                  ap (λ - → [ x ⁻ ] ++ [ - ]) ((inv-invol x)⁻¹) , refl)

 inv-property : (s : FA) → s ++ inv s ∾ []
 inv-property []      = srt-reflexive _▷_ []
 inv-property (x ∷ s) = γ
  where
   IH : s ++ inv s ∾ []
   IH = inv-property s

   γ = [ x ] ++ s ++ inv s ++ [ x ⁻ ]   ∾⟨ I ⟩
       [ x ] ++ (s ++ inv s) ++ [ x ⁻ ] ∾⟨ II ⟩
       [ x ] ++ [ x ⁻ ]                 ∾⟨ III ⟩
       []                               ∾∎
    where
     I   = =-∾  (ap (x ∷_) (++-assoc s (inv s) [ x ⁻ ])⁻¹)
     II  = ++-cong-right [ x ] (++-cong-left _ _ _ IH)
     III = inv-lemma x

 inv-property' : (s : FA) → inv s ++ s ∾ []
 inv-property' []      = srt-reflexive _▷_ []
 inv-property' (x ∷ s) = γ
  where
   γ = (inv s ++ [ x ⁻ ]) ++ (x ∷ s)    ∾⟨ I ⟩
       inv s ++ ([ x ⁻ ] ++ [ x ] ++ s) ∾⟨ II ⟩
       inv s ++ ([ x ⁻ ] ++ [ x ]) ++ s ∾⟨ III ⟩
       inv s ++ s                       ∾⟨ IV ⟩
       []                               ∾∎
    where
     I   = =-∾ (++-assoc (inv s) [ x ⁻ ] (x ∷ s))
     II  = =-∾ (ap (inv s ++_) ((++-assoc [ x ⁻ ] [ x ] s)⁻¹))
     III = ++-cong-right (inv s) (++-cong-left _ _ _ (inv-lemma' x))
     IV  = inv-property' s

\end{code}

The insertion of generators is left cancellable before quotienting:

\begin{code}

 η-lc : (a b : A) → η a ≡ η b → a ≡ b
 η-lc a b = ap f
  where
   f : FA → A
   f []            = a
   f ((n , c) ∷ s) = c

\end{code}

Now we should be able to prove this from the Church-Rosser property,
which will give that the insertion of generators is injective after
quotienting:

\begin{code}
{-
 η-∾ : (a b : A) → η a ∾ η b → a ≡ b
 η-∾ a b e = ?

 η-∾ₚ : (a b : A) → is-set A → η a ∾ₚ η b → a ≡ b
 η-∾ₚ = by η-∾ because A is a set and hence a ≡ b is a
        proposition and because η a ∾ₚ η b is ∥ η a ∾ η b ∥
-}
\end{code}

To be continued.

TODO. Quotient FA to get the free group, with a proof that the insertion
of generators is left-cancellable and hence, being a map of sets, an
embedding.
