#!/bin/bash
mkdir -p tmp/tmp-illiterate
ghc --make illiterator.hs
rm -f tmp/tmp-illiterate/*agda

for i in $( ls | grep ".lagda" | grep -v "~" ); do
    cat ${i} | ./illiterator > tmp/tmp-illiterate/${i%%.*}.agda
done
